name: Automate iOS Build and TestFlight upload

on:
  push:
    branches:
      - main

jobs:
  build_and_upload:
    name: Build and Upload
    runs-on: macos-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Xcode
        run: sudo xcode-select --switch /Applications/Xcode.app
        
      - name: Print Bundle Identifier
        run: |
         # Retrieve bundle identifier from Info.plist
         bundle_identifier=$(defaults read $PWD/TestCICD/Info.plist CFBundleIdentifier)
         echo "Bundle Identifier: $bundle_identifier"
         echo "BUNDLE_IDENTIFIER=$bundle_identifier" >> $GITHUB_ENV

      - name: Install CocoaPods
        run: |
          gem install cocoapods
          pod install
          
      - name: Download and Install Provisioning Profile
        run: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          echo "$PROVISIONING_PROFILE" | base64 --decode > ~/Library/MobileDevice/Provisioning\ Profiles/f688cf76-ff7c-4f2c-ae85-97e5a342d983.mobileprovision
        env:
          PROVISIONING_PROFILE: ${{ secrets.PROVISIONING_PROFILE}}
          
      - name: Clean Project
        run: xcodebuild clean -workspace TestCICD.xcworkspace -scheme TestCICD
        
      - name: Print Archive Locationn
        run: |
          # Print the current working directory
          echo "Current Directory: $(pwd)"
          # Print the location of the archive
          echo "Archive Location: $(pwd)/TestCICD.xcarchive"

      - name: Build IPAA
        run: xcodebuild -workspace "TestCICD.xcworkspace" -scheme "TestCICD" -configuration Release clean archive -archivePath "TestCICD.xcarchive" CODE_SIGNING_ALLOWED=NO -allowProvisioningUpdates
        
      - name: Export IPA
        run: xcodebuild -exportArchive -archivePath "TestCICD.xcarchive" -exportPath "TestCICD" -exportOptionsPlist "TestCICD/ExportOptions.plist" -allowProvisioningUpdates

      - name: List Files
        run: ls -lh

      - name: Install Transporter
        run: brew install --cask transporter

      - name: Upload to TestFlight
        run: transporter upload -package SampleCICD.ipa -username ${{ secrets.APPLE_ID_USERNAME }} -password ${{ secrets.APP_SPECIFIC_PASSWORD }} -itc_provider ${{ secrets.ITC_TEAM_ID }}
